### ISSUE TITLE
Scripts cannot write to `/kubemod-crt` directory under some scenarios

### ISSUE THREAD

**Issue by gmahomarf** [kubemod/kubemod-crt#7]
In some environments, like OpenShift, certain security policies may restrict the numeric range for UID/GID's that can be used to run a container. A container in this scenario will run with a different UID/GID than the hardcoded values in the Dockerfile.

This presents a problem because the scripts don't have permission to write to the `/kubemod-crt` directory, which causes the cert generation to fail. The way I see it, there are two options:

1. Make the `/kubemod-crt` directory writeable for everyone (I have opened a PR with this change. See #6)
2. Change the scripts to create a directory inside `/tmp` and write the certs there

**Comment by vassilvk** [comment]
Hi @gmahomarf,

I am reading https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids (section **Traditional Applications and UIDs**) and it seems like the recommendation is to make `/kubemod-crt` readable by group 0.

Do you think this would do the trick? I don't have access to OpenShift to test.

**Comment by gmahomarf** [comment]
Hi @vassilvk. Thanks for the quick reply.

I will give it a try tomorrow. However, I'm not sure that will work, since the issue is with reading, not with writing. The script currently fails when it tries to create `ca.pem`

**Comment by vassilvk** [comment]
Oops, sorry, by "readable", I meant "readable/writable" 🤦‍♂️

**Comment by gmahomarf** [comment]
Hi, @vassilvk 

Making the directory writeable for group 0 (`root`) works. I have updated my PR

**Comment by vassilvk** [comment]
Closed by #6
