### ISSUE TITLE
User nonroot lost write access to kubemod-crt after 1.1.2

### ISSUE THREAD

**Issue by vassilvk** [kubemod/kubemod-crt#8]
Steps to reproduce:

- Run a 1.1.2 container with shell:
```
docker run -it --rm kubemod/kubemod-crt:v1.1.2 sh
```
- While in the container shell:
```
cd /kubemod-crt
touch test
```
The above yields `touch: test: Permission denied`.

This is a problem when deploying KubeMod to non-OpenShift Kubernetes distributions as not all distributions make the container user a member of group `root`.

Suggested solution:
Roll back the changes made by #6 and make /kubemod-crt writable by everyone, as per the original suggestion by @gmahomarf.

**Comment by gmahomarf** [comment]
Hi @vassilvk.

I missed that in my changes. #9 should fix it (I tested locally)

**Comment by vassilvk** [comment]
Thank you @gmahomarf!
I'll try and test the new bits this week with the goal of releasing with KubeMod v0.14.0.
